# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages: 
- stage: Build
  jobs:
  - job: Build
    steps: 
    - task: NuGetToolInstaller@1
    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'
    - task: VSBuild@1
      inputs:
        solution: '**\*.sln'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

- stage: Test
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: Run_Tests
    steps: 
    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        projects: '**/*TicTacToeTests/*.csproj'
        configuration: '--self-contained true -r win-x86 --configuration $(buildConfiguration)'
        testRunTitle: 'Running Unit Tests'
